import { StateValues } from 'features/states/types'

export const charData: StateValues = {
  name: '光天使安潔莉卡',
  url: 'https://raw.githubusercontent.com/fribbels/Fribbels-Epic-7-Optimizer/main/data/cachedimages/c6062_s.png',
  current: {
    atk: 1200,
    def: 1500,
    health: 15000,
    spd: 220,
    cri: 15,
    crd: 150,
    eff: 150,
    res: 130,
    weapon: 92,
    helmet: 101,
    armor: 89,
    necklace: 89,
    ring: 96,
    boots: 94,
    weaponSet: 'spd',
    helmetSet: 'spd',
    armorSet: 'hit',
    necklaceSet: 'spd',
    ringSet: 'spd',
    bootsSet: 'hit',
    set1: 'spd',
    set2: 'hit',
    set3: '',
  },
  expect: {
    atk: 2000,
    def: 2000,
    health: 20000,
    spd: 220,
    eff: 200,
    res: 200,
    weaponSet: 'spd',
    set1: 'spd',
    set2: 'hit',
    set3: '',
  },
  username: 'Test1',
}
